name: Consumer to Pactflow

on:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://itv-fe.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  VERSION: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests and generate pact files
        run: |
          cd consumer-spa
          npm install -g pnpm@7
          pnpm install
          pnpm build
          pnpm cypress:up
          pnpm cypress:run
          pnpm cypress:down
      - name: Publish to Pactflow
        run: |
          export PACT_BROKER_TOKEN=${{ env.PACT_BROKER_TOKEN }}
          export PACT_BROKER_BASE_URL=${{ env.PACT_BROKER_BASE_URL }}
          ./.github/actions/publish-consumer.sh
