name: Consumer to Pactflow

on:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://itv-fe.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  VERSION: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests and generate pact files
        run: |
          cd consumer-spa
          npm install -g pnpm@7
          pnpm install
          pnpm build
          pnpm cypress:up
          pnpm cypress:run
          pnpm cypress:down
      - name: Publish to Pactflow
        run: |
          pwd
          cd $GITHUB_WORKSPACE
          export BRANCH=${GITHUB_REF:11}
          export PACT_FILES_LOCATION=consumer-spa/cypress/pacts
          export VERSION=1.0.0
          docker run --rm \
            -v $(pwd):/$(pwd) \
            -w $(pwd) \
            -e PACT_BROKER_BASE_URL \
            -e PACT_BROKER_TOKEN \
            pactfoundation/pact-cli:latest \
            pact-broker publish $PACT_FILES_LOCATION \
            --consumer-app-version $VERSION \
            --broker-base-url $PACT_BROKER_BASE_URL \
            --branch main