name: Provider to Pactflow

on:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://itv-fe.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  VERSION: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🧪 Test and upload to Pactflow 📈
        run: BRANCH=${GITHUB_REF:11} make publish_provider_contract
